apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-helm.fullname" . }}
  
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontend-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend-helm.selectorLabels" . | nindent 8 }}
    spec:
     containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          